version: "3"
services:
  ecollect:
    image: migutak/ecollect:1.0.0
    deploy:
      replicas: 1
    container_name: ecollect
    restart: always
    ports:
      - "80:80"
    networks:
    - ecol-network

  ecollect_apis:
    image: migutak/ecollect_apis:1.0.0
    deploy:
      replicas: 2
    container_name: ecollect_apis
    restart: always
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
    ports:
      - "8000:8000"
    networks:
    - ecol-network

  oracledb_node:
    image: migutak/oracledbnode:1.0.0
    deploy:
      replicas: 2
    container_name: oracledb_node
    restart: always
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_CONNECTIONSTRING=${DB_CONNECTIONSTRING}
    ports:
      - "6001:6001"
    networks:
    - ecol-network

  uploads:
    image: migutak/uploads:1.0.0
    deploy:
      replicas: 2
    container_name: uploads
    restart: always
    environment:
      - CORS=http://localhost:7000
    volumes:
      - /opt/uploads:/var/uploads
    ports:
      - "4000:4000"
      - "5000:5000"
      - "5001:5001"
      - "3000:3000"
    networks:
    - ecol-network

  docxletters:
    image: migutak/docxletters:1.0.0
    deploy:
      replicas: 3
    container_name: docx
    restart: always
    volumes:
      - /opt/demands:/app/demands/
    environment:
      - FILEPATH=/app/demands/
      - IMAGEPATH=/app/docxletters/routes/
    ports:
      - "8004:8004"
    networks:
    - ecol-network

networks:
  ecol-network:
    driver: overlay