apiVersion: v1
kind: PersistentVolume
metadata:
  name: demands-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  reclaimPolicy: Retain
  hostPath:
    path: "/app/nfs/demands"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demands-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi