  ---
    apiVersion: v1
    kind: Service
    metadata:
      name: ecollect
    spec:
      selector:
        app: ecollect
      type: NodePort
      ports:
      - protocol: TCP
        port: 80
        targetPort: 80
        nodePort: 30030
    
    ---
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: ecollect-deployment
      labels:
        app: ecollect
    spec:
      replicas: 3
      selector:
        matchLabels:
          app: ecollect
      template:
        metadata:
          labels:
            app: ecollect
        spec:
          containers:
          - name: ecollect
            image: 172.16.204.72:5000/ecollect:u.0.0
            ports:
            - containerPort: 80
    