---
    apiVersion: v1
    kind: Service
    metadata:
      name: rabbitmq3
    spec:
      selector:
        app: rabbitmq3
      type: NodePort
      ports:
      - protocol: TCP
        port: 15672
        targetPort: 15672
        nodePort: 30015
    
    ---
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: rabbitmq3-deployment
      labels:
        app: rabbitmq3
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: rabbitmq3
      template:
        metadata:
          labels:
            app: rabbitmq3
        spec:
          containers:
          - name: rabbitmq3
            image: 172.16.204.74:5000/rabbitmq:3-management
            ports:
            - containerPort: 15672
    