---
apiVersion: v1
kind: Service
metadata:
  name: my-uploads
  labels:
    app: my-uploads
spec:
  type: NodePort
  ports:
    - port: 8600
      nodePort: 30036
      name: http
  selector:
    app: my-uploads
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-uploads
spec:
  selector:
    matchLabels:
      app: my-uploads
  replicas: 1
  template:
    metadata:
      labels:
        app: my-uploads
    spec:
      volumes:
        - name: emp-volume
          emptyDir: {}
        - name: uploads-pv-storage
          persistentVolumeClaim:
            claimName: upload-pvc
      containers:
      - name: uploads-container
        volumeMounts:
          - name: uploads-pv-storage
            mountPath: /tmp/uploads
        image: migutak/express-fileupload-docker
        ports:
          - containerPort: 8600
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
