  ---
    apiVersion: v1
    kind: Service
    metadata:
      name: serviceproviders
    spec:
      selector:
        app: serviceproviders
      type: NodePort
      ports:
      - protocol: TCP
        port: 80
        targetPort: 80
        nodePort: 30060
    
    ---
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: serviceproviders-deployment
      labels:
        app: serviceproviders
    spec:
      replicas: 2
      selector:
        matchLabels:
          app: serviceproviders
      template:
        metadata:
          labels:
            app: serviceproviders
        spec:
          containers:
          - name: serviceproviders
            image: 172.16.204.74:5000/serviceproviders:1.0.0
            ports:
            - containerPort: 80
    