  ---
    apiVersion: v1
    kind: Service
    metadata:
      name: sms
    spec:
      selector:
        app: sms
      type: NodePort
      ports:
      - protocol: TCP
        port: 7000
        targetPort: 7000
        nodePort: 30070
    
    ---
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: sms-deployment
      labels:
        app: sms
    spec:
      replicas: 2
      selector:
        matchLabels:
          app: sms
      template:
        metadata:
          labels:
            app: sms
        spec:
          containers:
          - name: sms
            image: 172.16.204.74:5000/sms
            ports:
            - containerPort: 7000
    