version: "3"

services:
   mysql4:
     image: mysql:5.6
     restart: always
     container_name: mysql4
     environment:
       MYSQL_ROOT_PASSWORD: root
     volumes:
       - "c:/mysqldataoracle:/var/lib/mysql"
     ports:
       - "3310:3306"
     networks:
     - pm-net

   processmaker:
     depends_on:
     - mysql4
    # image: processmaker/httpd
     image: kumadocker/processmaker
     container_name: pmaker
     restart: always
     ports:
       - "8090:80"
     restart: always
     environment:
       URL: "127.0.0.1:8090"
     networks:
      - pm-net


networks:
  pm-net:
    driver: bridge

# docker run -it -d --name pmaker -e URL:172.16.19.151:8085 -p 8085:80 kumadocker/processmaker
# docker run -it -d --name mysql -e MYSQL_ROOT_PASSWORD:root -v /app/mysqldata:/var/lib/mysql -p 3306:3306 mysql:5.6
# docker run -it -d --name mymaker kumadocker/processmaker
# docker run -it -d --name mymaker eltercera/docker-processmaker
# docker run -itd --privileged --name centos centos:7
