version: "3"

services:
   mysql3:
     image: mysql:5.6
     restart: always
     container_name: mysql3
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: root
     volumes:
       - "c:/mysqldata3:/var/lib/mysql"
     ports:
       - "3305:3306"
     networks:
     - pm-net

   processmaker:
     depends_on:
     - mysql3
     image: migutak/processmaker:oracle
     container_name: processmaker
     restart: always
     ports:
       - "8088:80"
     restart: always
     environment:
       URL: "127.0.0.1:8088"
     networks:
      - pm-net


networks:
  pm-net:
    driver: bridge

# docker run -it -d --name pmaker -e URL:172.16.19.151:8085 -p 8085:80 digitaloak/processmaker-ce:latest
# docker run -it -d --name mysql -e MYSQL_ROOT_PASSWORD:root -v /app/mysqldata:/var/lib/mysql -p 3306:3306 mysql:5.6