version: '3'

services:
  registry:
    container_name: registry
    image: registry:2
    restart: always
    ports:
    - "5000:5000"
    volumes:
      - /app/docker-registry:/var/lib/registry
    networks:
      - ecol-network
    
networks:
  ecol-network:
    driver: bridge

